language: node_js

sudo: false

matrix:
  include:
    - node_js: 10
      script:
        - npm test
    - node_js: 12
      script:
        - npm test
      after_script:
        - npm run upload-coverage